apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaibackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openaibackend
  template:
    metadata:
      labels:
        app: openaibackend
    spec:
      nodeSelector:
        agentpool: agentpool
      containers:
      - name: openaibackend
        image: acropenai2.azurecr.io/backend:26

        # FIX: expose containerPort 8080
        ports:
          - containerPort: 8080

        env:
          - name: AZURE_OPENAI_ENDPOINT
            value: "https://openai11234.openai.azure.com"
          - name: AZURE_OPENAI_DEPLOYMENT
            value: "gpt-5-nano"
          - name: REDIS_HOST
            value: "aiforredis.uksouth.redis.azure.net"
          - name: REDIS_PORT
            value: "10000"
          - name: AZURE_CLIENT_ID
            value: "67149d02-31af-4e28-a925-633f1d4c045d"
          


---
apiVersion: v1
kind: Service
metadata:
  name: openaibackend-svc
spec:
  type: LoadBalancer
  selector:
    app: openaibackend
  ports:
    - name: http
      port: 80
      targetPort: 8080
