apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaibackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openaibackend
  template:
    metadata:
      labels:
        app: openaibackend
        
    spec:
    
      nodeSelector:
        agentpool: agentpool  # <-- This targets the specific node pool
      containers:
      - name: openaibackend
        image: acropenai2.azurecr.io/backend:latest
        env:
            - name: AZURE_OPENAI_ENDPOINT
              value: https://foundry112.openai.azure.com
            - name: AZURE_OPENAI_DEPLOYMENT
              value: "gpt-5-nano"
            - name: REDIS_HOST
              value: "redisforopenai.uksouth.redis.azure.net"
            - name: REDIS_PORT
              value: "10000"
       


---
apiVersion: v1
kind: Service 
metadata:
  name: openaibackend-svc
spec:
  type: ClusterIP
  selector:
    app: openaibackend
  ports: 
    - name: http
      port: 80
      targetPort: 8080
